CLI: replace uses of '{s}' in format strings with {q}
Example output:

$ zig build-exe "-freference-trace=b\" 'ah"
error: unable to parse reference_trace count "b\" 'ah": InvalidCharacter

Before this change:
error: unable to parse reference_trace count 'b" 'ah': InvalidCharacter

Zig does not have single-quoted strings, plus it wasn't escaping the
single quotes anyway. Better to use actual double quote string syntax
than to fake a fake syntax.